# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
skipsdist=True
skip_missing_interpreters = True
envlist = bundle-integration

[vars]
tst_path = {toxinidir}/tests

[testenv:integration]
description = Run integration tests
deps =
    -r{toxinidir}/requirements-integration.txt
    juju # must be compatible with the juju version installed by CI
    pytest
    pytest-operator
commands =
    pytest -vv --tb native --log-cli-level=INFO --color=yes -s {posargs} {[vars]tst_path}/integration
