# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
skipsdist=True
skip_missing_interpreters = True
env_list = fmt, lint, integration

[testenv]
allowlist_externals = poetry
deps =
    poetry

[vars]
tst_path = {toxinidir}/tests

[testenv:fmt]
commands =
    poetry install --with fmt --no-root
    isort {[vars]tst_path}
    black {[vars]tst_path}
description = Apply coding style standards to code

[testenv:lint]
commands =
    poetry install --with lint --no-root
    codespell {toxinidir}/. --skip {toxinidir}/./.git --skip {toxinidir}/./.tox \
      --skip {toxinidir}/./build --skip {toxinidir}/./lib --skip {toxinidir}/./venv \
      --skip {toxinidir}/./.mypy_cache \
      --skip {toxinidir}/./icon.svg --skip *.json.tmpl \
      --skip {toxinidir}/./poetry.lock
    ruff check {[vars]tst_path}
    ruff format --check --diff {[vars]tst_path}
    black --check {[vars]tst_path}
    pyright {posargs}
description = Check code against coding style standards

[testenv:integration]
description = Run integration tests
deps =
    juju # must be compatible with the juju version installed by CI
    pytest
    pytest-operator
    {[testenv]deps}
commands =
    poetry install --with integration --no-root
    pytest -vv --tb native --log-cli-level=INFO --color=yes -s {posargs} {[vars]tst_path}/integration
