name: CI

on:
  workflow_call:

jobs:
  terraform-checks:
    name: Terraform
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-checks-solution.yaml@main
    with:
      module-path: terraform/

  lint:
    name: Linting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: pipx install tox
      - run: tox -e lint

  integration-test:
    name: Integration tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        kserve-mode:
        - knative  # formerly "serverless"
        - standard  # formerly "rawdeployment"

    steps:
      - name: Maximise GH runner space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install tox
        run: pipx install tox

      - name: Set up environment
        run: |
          sudo apt-get remove -y docker-ce docker-ce-cli containerd.io
          sudo rm -rf /run/containerd
          sudo snap install concierge --classic
          sudo concierge prepare --trace

      - name: Run integration tests with KServe in ${{ matrix.kserve-mode }} mode
        run: |
          juju add-model inference-test
          tox -e integration -- --kserve-mode ${{ matrix.kserve-mode }} --model inference-test

      - run: juju status --model inference-test
        if: failure()
